# HACS configuration for R Volution Player
name: R Volution Player
content_in_root: false
zip_release: true
filename: ha_r_volution_player.zip
render_readme: true

# Optional: Specify the domains this repository provides
domains:
  - media_player

